# Generated by Django 4.0.5 on 2022-07-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0003_student_memories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='student',
        ),
        migrations.AddField(
            model_name='memories',
            name='stuid',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
