# Generated by Django 4.0.5 on 2022-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0005_alter_memories_stuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
