# Generated by Django 4.0.5 on 2022-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0006_student_email_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='x', max_length=1000),
        ),
    ]
