# Generated by Django 4.0.5 on 2022-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0007_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='x', upload_to=''),
        ),
    ]
