# Generated by Django 4.0.5 on 2022-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0008_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='2.png', upload_to=''),
        ),
    ]
