# Generated by Django 4.0.5 on 2022-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0011_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ybyear', models.CharField(max_length=4)),
            ],
        ),
    ]
