# Generated by Django 4.0.5 on 2022-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0013_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
