# Generated by Django 4.0.5 on 2022-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0014_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
