# Generated by Django 4.0.5 on 2022-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0015_alter_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='None', max_length=20)),
            ],
        ),
    ]
