# Generated by Django 4.0.5 on 2022-07-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0016_branc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branc',
            new_name='Branch',
        ),
    ]
