# Generated by Django 4.0.5 on 2022-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0017_rename_branc_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
