# Generated by Django 4.0.5 on 2022-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0019_alter_student_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
