# Generated by Django 4.0.5 on 2022-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0020_alter_student_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderuname', models.CharField(default='', max_length=50)),
                ('recieveruname', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
