# Generated by Django 4.0.5 on 2022-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0022_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='branch',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
