# Generated by Django 4.0.5 on 2022-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0023_person_branch_person_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='1920_1.jpg', upload_to=''),
        ),
    ]
