# Generated by Django 4.0.5 on 2022-07-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0025_alter_person_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
