# Generated by Django 4.0.5 on 2022-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0028_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
