# Generated by Django 4.0.5 on 2022-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0029_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='1920_1.jpg', upload_to=''),
        ),
    ]
