# Generated by Django 4.0.5 on 2022-07-18 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ybapp', '0030_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='stuid',
        ),
        migrations.AddField(
            model_name='memories',
            name='memuname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='memories',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
