# Generated by Django 4.0.5 on 2022-07-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0031_remove_memories_stuid_memories_memuname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='user',
        ),
    ]
