# Generated by Django 4.0.5 on 2022-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0032_remove_memories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
