# Generated by Django 4.0.5 on 2022-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0033_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
