# Generated by Django 4.0.5 on 2022-07-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0034_alter_student_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
