# Generated by Django 4.0.5 on 2022-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0035_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quote',
            field=models.CharField(default='None', max_length=5000),
        ),
    ]
